server:
  port: ${PORT:8080}

spring:
  webflux:
    problem-details:
      enabled: true
  application:
    name: Dinno-Users
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/dinno_users}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/dinno_users}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/dinno_users}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

    register-with-eureka: true
    fetch-registry: true
  instance:

    prefer-ip-address: true
   
    lease-renewal-interval-in-seconds: 30