server:
  port: ${PORT:8080}

spring:
  webflux:
    problem-details:
      enabled: true
  application:
    name: Dinno-Users
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/dinno_users}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/dinno_users}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    enabled: false
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/dinno_users}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true

    lease-renewal-interval-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
